version: '3'
services:
  redis-server: 
    image: 'redis'
    container_name: redis
    ports:
      - "6379:6379"
  node-app:
    build: .
    ports:
      - "7071:7071"
  db_cloud:
    tty: true
    image: mysql:5.7
    container_name: dbcloud
    build: 
      context: .
      dockerfile: dockerfile-db
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db_cloud"]
        interval: 2s
        timeout: 2s
        retries: 10
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'