version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: brokermosq
    tty: true
    volumes:
      - ./../mosquitto/config/:/mosquitto/config/:ro
      - ./../mosquitto/log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  
  pubsubjs:
    tty: true
    build:
      context: ./..
      dockerfile: docker/dockerfile-pubsubjs
    container_name: pubsubjs
    ports:
      - "7071:7071"
    volumes:
      - nodeapp:/usr/app/
      - nodeapp:/usr/app/node_modules
      
# Names our volume
volumes:
  nodeapp:
  data:
      